create exel report generator and email sender
KateGuz/spock pull request #26
Opened 2017-02-12 16:03 UTC by DmitriyShalimov

2017-02-12 17:56 UTC, KateGuz requested changes
В целом код хороший и структурированный. Кроме пары странных мест с генерацией отчетов и закрытием потоков, все выглядит на приличном уровне. 
Единственное что, почитай еще раз таску https://trello.com/c/BaupbiGJ/32-t-4-generate-excel-or-pdf-report 

Задача сложная, ответственная и комплексная. Ты из за невнимательности потерял по пути пол фичи.

Где : 
From client perspective:

Report generation is async. Admin can place request for report generation, and get email notification when report done, with link to the report.

REST usage

1) Admin can request report via REST. Request should have security header to confirm that it's authorized.
2) Please use HTTP method:

POST to add report request
PUT to check status report processing
GET to get link of report which is already finished
DELETE to remove report request or report results

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/dao/impl/JdbcLotDao.java
> +            queryy.append("l.startDate>'").append(reportOption.getStartDate()).append("' AND ").append("l.startDate<'").append(reportOption.getEndDate()).append("');");
1) queryy?
2) Лучше писать вертикально, есть правило относительно максимальной длинны строки в коде. Учитывая что сейчас строка вылазит за экран ты его нарушил. Обрати внимание на серую вертикальную полосу справа в редакторе Idea.
3) Может быть генерация query должна происходить в QueryGenerator? А то получается слегка не послежовательно. Если тебе кажется что класс QueryGenerator перегружен, возможно стоит создать специфический генератор для вот этих конкретных запросов. Но обходить архитектуру где у тебя запросы генерируются в специальных классах, ты не можешь.
4) WHERE, AND стоит вынести в константы? Что бы они не удалялись как локальные переменные метода после выхода из этого метода.

2017-02-12 17:56 UTC, KateGuz commented on pom.xml
> +            <version>3.12</version>
1) Вынести версию в проперти мавена, если она используеться в двух местах? 
2) Нет ли в poi-ooxml транзитивной (внутренней) зависимости за poi?

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/entity/ReportOption.java
> +    private String type;
enum :cake:

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/impl/LotServiceImpl.java
> +    private ExelReportGenerator exelReportGenerator;
код не используется

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/impl/ReportServiceImpl.java
> +    private ExelReportGenerator exelReportGenerator;
Excel != Exel

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/impl/ReportServiceImpl.java
> +        emailSender.sendEmail(reportOption.getEmail(),reportOption.getDocumentName());
Забыл отформатировать

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +                return new PasswordAuthentication(username, password);
Заменить на лямбду

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +        if (((User) session.getAttribute("loggedUser")).getType().equals(UserType.ADMIN)) {
Это не асинхронная генерация отчета. 
Пользователь ждет. Он ждать не должен. 
Метод контроллера должен добавлять запрос в некую коллекцию.
Плюс должен быть scheduled thread который периодически проверяет не появились ли новые запросы на отчеты, и если появились, то генерирует отчет и отправляет ссылки на отчет по почте.

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +        InputStream inputStream = getClass().getClassLoader().getResourceAsStream("mailSender.properties");
Давай вычитаем проперти с помощью Spring, а не вручную.

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +        String file="D://spock/report/"+name+".xls";
Относительный путь а не полный

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +        Workbook book = new HSSFWorkbook();
почему не XSSFWorkbook?

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +        Cell category = row.createCell(3);
Сделать циклом, итерацией по массиву колонок.

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +        Cell category = row.createCell(3);
И вынести в отдельный метод создание этого хедера.

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +            row = sheet.createRow(i++);
Два цикла. Один в другом. Первым ты создаешь строки, вторым колонки.

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +            e.printStackTrace();
хм....

2017-02-12 17:56 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +            book.write(new FileOutputStream(file));
Что будет если ты закрывать потоки ввода вывода в Java?

2017-02-12 17:56 UTC, KateGuz commented on src/main/resources/root-context.xml
> +    <bean id="username" class="java.lang.String">
1) Почему часть проперти в проперти файлах, а эти два в Spring XML ? 
2) Обязательно ли указывать логин и пароль от почты с которой отправляешь?

2017-02-18 00:29 UTC, DanyloZ commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +                return new PasswordAuthentication(username, password);
Лямбду можно сделать только из интерфейса с одним методом, а Authenticator - это абстрактный класс, из него нельзя.

2017-02-18 03:56 UTC, DanyloZ commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +            row = sheet.createRow(i++);
цикл по полям лота - это через рефлексию?
В лоте поля разных типов, и некоторые поля мы приводим к стрингу через String.valueOf()
Или я чего-то не понял, или как-то сложно все выходит :)

2017-02-19 19:04 UTC, DmitriyShalimov commented on src/main/resources/root-context.xml
> +    <bean id="username" class="java.lang.String">
логин и пароль от почты надо указывать иначе не сможет отправить письмо

2017-02-19 19:05 UTC, DmitriyShalimov commented on src/main/java/ua/spock/spock/utils/ExelReportGenerator.java
> +        Workbook book = new HSSFWorkbook();
Да, нужен XSSFWorkbook-он для более новых файлов Microsoft Office

2017-02-27 19:19 UTC, KateGuz requested changes
молодец, все работает и написано вроде чисто.
но мне не понравилось то решение которое ты принял о хранении отчетов в варке. предлагаю этот момент переделать. остальные замечания мелкие.

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +            ReportOption reportOption = ReportOptionJsonParser.jsonToReportOption(json, user.getName());
почему ReportOption? странное название для ReportRequest-а)

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/entity/ReportOption.java
> +    private String userName;
зачем здесь имя юзера и название документа?

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/entity/ReportOptionType.java
> +    public static ReportOptionType getRportOptionTypeById(String id) {
опечатка

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/entity/ReportOptionType.java
> +    STARTED("started"), ENDED("ended");
не очевидные названия. это должен быть тип отчета. у тебя получается, что отчет стартед или эндед

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/scheduler/ReportProcessingScheduler.java
> +public class ReportProcessingScheduler {
почему это все не может быть просто в репорт сервисе? зачем отдельный класс?

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/utils/ReportOptionJsonParser.java
> +            reportOption.setDocumentName("report-" + userName + "-" + LocalDateTime.now().format(dateTimeFormatter));
в таске написано, какое имя должно быть у отчета. 
имя добавлять - не вариант. у нас в базе имя - это имя и фамилия, пробел ламает ссылку

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/scheduler/ReportProcessingScheduler.java
> +    @Scheduled(fixedDelay = 2 * 24 * 60 * 60 * 1000)
почитай таску. там написано, когда удалять отчеты

2017-02-27 19:19 UTC, KateGuz commented on src/main/java/ua/spock/spock/service/scheduler/ReportProcessingScheduler.java
> +        reportFolderPath = servletContext.getRealPath("/report/");
я думаю, это не хорошее решение. получается, мы храним файлы в war, а это плохо. 1) после редеплоя war мы потяеряем все файлы. 2) для некоторых серверов getRealPath() вообще будет возвращать null

я бы хранила отчеты в бд. добавила бы табличку и безопасно там хранила
а пользователю на почту отправляла бы ссылку типа report/{reportId}, такой запрос бы обрабатывала в контроллере и возвращала отчет
предлагаю так сделать

2017-02-27 22:01 UTC, DanyloZ commented on src/main/java/ua/spock/spock/entity/ReportOption.java
> +    private String userName;
имя вставляется в имя файла, на случай если два админа одновременно создадут запрос на репорт :)

2017-02-27 22:05 UTC, DanyloZ commented on src/main/java/ua/spock/spock/entity/ReportOption.java
> +    private String userName;
прочитал камент ниже, переделаю

2017-02-27 22:08 UTC, DanyloZ commented on src/main/java/ua/spock/spock/utils/ReportOptionJsonParser.java
> +            reportOption.setDocumentName("report-" + userName + "-" + LocalDateTime.now().format(dateTimeFormatter));
репорты в этой версии хранятся в одной папке, тоесть если создать два репорта в один день,  то второй затрет первый. Но я переделаю на хранение в базе, так что ок.

2017-02-27 22:09 UTC, DanyloZ commented on src/main/java/ua/spock/spock/service/scheduler/ReportProcessingScheduler.java
> +    @Scheduled(fixedDelay = 2 * 24 * 60 * 60 * 1000)
каждый понедельник Июля? Мадам знает толк в извращениях :)

2017-03-03 09:53 UTC, Rooman requested changes
Где тесты?!!!

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +            ReportRequest reportRequest = ReportRequestJsonParser.jsonToReportOption(json);
переименовать метод который парсит

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +        response.getOutputStream().write(report);
А можно было сразу OutputStream в методе получить, без HttpServletResponse?

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/dao/ReportDao.java
> +    byte[] getReport(int reportId);
должна быть сущность репорта. А то получается херня. На сейв у тебя инпут стрим, на гет у тебя массив байт

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/entity/ReportRequestType.java
> +        return null;
throw new IllegalArgumentExcepion("No reportType found for id: " + id);

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/service/ReportService.java
> +    int saveReport(InputStream report);
сюда тоже сущность репорта

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/service/impl/ReportServiceImpl.java
>  public class ReportServiceImpl implements ReportService {
Класс сделан ништяково, только на сущность рпот переделай. Убери стримы и массивы байт

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +    @Resource(name = "mailSenderProperties")
huge improvement 🍰

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/utils/EmailSender.java
>              throw new RuntimeException(e);
добавить бы сюда логгирования

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +        result = "http://" + host + ":8080/report/" + reportId + "/" + documentName + ".xlsx";
хуета. что за хаодкод? почему нельзя все в проперти вынести. Вебсервер всегда по 8080?

2017-03-03 09:53 UTC, Rooman commented on src/main/java/ua/spock/spock/utils/EmailSender.java
> +        result = "http://" + host + ":8080/report/" + reportId + "/" + documentName + ".xlsx";
комментарий выше, едиственный написаный Катей

2017-03-03 09:53 UTC, Rooman commented
Даня давай, осталось последнее усилие

2017-03-03 18:51 UTC, DanyloZ commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +        response.getOutputStream().write(report);
можно, но респонс все равно нужен, чтобы установить setContentType. Хотя работает и без него...

2017-03-03 19:58 UTC, Rooman commented on src/main/java/ua/spock/spock/controller/ReportController.java
> +        response.getOutputStream().write(report);
не заметил

2017-03-04 06:51 UTC, KateGuz requested changes
1 замечание и тесты не нашла

2017-03-04 06:51 UTC, KateGuz commented on src/main/resources/logback.xml
> +            <fileNamePattern>C:/spock/log/spock_%d{yyyy-MM-dd}.log.%i</fileNamePattern>
почему путь абсолютный?

2017-03-06 02:33 UTC, merged